CREATE TABLE usuarios (
    id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    email VARCHAR(100) NOT NULL UNIQUE,
    nome VARCHAR(100) NOT NULL,
    senha VARCHAR(255) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE tarefas (
    id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    fk_usuario_id INT UNSIGNED NOT NULL,
    titulo VARCHAR(100) NOT NULL,
    descricao TEXT,
    `data` DATETIME,
    `status` ENUM('PENDENTE', 'CONCLUIDA') DEFAULT 'PENDENTE',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (fk_usuario_id) REFERENCES usuarios(id)
);